/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Zukrina31
 */
public class Adminpage extends javax.swing.JFrame {

    /**
     * Creates new form Adminpage
     */
    public Adminpage() {
        initComponents();
        //So that the window size is consistent throughout
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Collect_payment = new javax.swing.JButton();
        Generate_report = new javax.swing.JButton();
        Confirm_booking = new javax.swing.JButton();
        View_cus_info = new javax.swing.JButton();
        View_car_info = new javax.swing.JButton();
        View_admin_info = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Admin_page.png"))); // NOI18N
        Background.setText("jLabel2");
        Background.setMaximumSize(new java.awt.Dimension(1366, 768));
        Background.setMinimumSize(new java.awt.Dimension(1366, 768));
        Background.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1370, 770);

        Logout.setText("jButton1");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout);
        Logout.setBounds(1189, 4, 160, 80);

        Collect_payment.setText("jButton2");
        getContentPane().add(Collect_payment);
        Collect_payment.setBounds(909, 214, 340, 160);

        Generate_report.setText("jButton3");
        getContentPane().add(Generate_report);
        Generate_report.setBounds(900, 500, 350, 180);

        Confirm_booking.setText("jButton5");
        getContentPane().add(Confirm_booking);
        Confirm_booking.setBounds(510, 610, 340, 160);

        View_cus_info.setText("jButton6");
        getContentPane().add(View_cus_info);
        View_cus_info.setBounds(100, 500, 340, 170);

        View_car_info.setText("jButton7");
        View_car_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_car_infoActionPerformed(evt);
            }
        });
        getContentPane().add(View_car_info);
        View_car_info.setBounds(100, 200, 340, 170);

        View_admin_info.setText("jButton8");
        View_admin_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_admin_infoActionPerformed(evt);
            }
        });
        getContentPane().add(View_admin_info);
        View_admin_info.setBounds(10, 0, 190, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        //Closes this page and goes back to the login page
        this.setVisible(false);
        Admin_login ob = new Admin_login();
        ob.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void View_admin_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_admin_infoActionPerformed
        // view admin profile
        admin_profile proAdmin = new admin_profile();
        this.setVisible(false);
        proAdmin.setVisible(true);
    }//GEN-LAST:event_View_admin_infoActionPerformed

    private void View_car_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_car_infoActionPerformed
        // view car information
        car_info carInfo = new car_info();
        this.setVisible(false);
        carInfo.setVisible(true);
    }//GEN-LAST:event_View_car_infoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Collect_payment;
    private javax.swing.JButton Confirm_booking;
    private javax.swing.JButton Generate_report;
    private javax.swing.JButton Logout;
    private javax.swing.JButton View_admin_info;
    private javax.swing.JButton View_car_info;
    private javax.swing.JButton View_cus_info;
    // End of variables declaration//GEN-END:variables
}
