/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author yibei
 */
public class Customer_Booking extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Booking
     */
    public Customer_Booking() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationTF = new javax.swing.JTextField();
        pdateTF = new javax.swing.JTextField();
        time1TF = new javax.swing.JTextField();
        ddateTF = new javax.swing.JTextField();
        time2TF = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        logoutBT = new javax.swing.JButton();
        searchBT = new javax.swing.JButton();
        returnBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        locationTF.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        locationTF.setBorder(null);
        getContentPane().add(locationTF);
        locationTF.setBounds(140, 200, 220, 60);

        pdateTF.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pdateTF.setBorder(null);
        getContentPane().add(pdateTF);
        pdateTF.setBounds(420, 200, 130, 70);

        time1TF.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        time1TF.setBorder(null);
        time1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time1TFActionPerformed(evt);
            }
        });
        getContentPane().add(time1TF);
        time1TF.setBounds(600, 200, 90, 50);

        ddateTF.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ddateTF.setBorder(null);
        getContentPane().add(ddateTF);
        ddateTF.setBounds(740, 200, 130, 70);

        time2TF.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        time2TF.setBorder(null);
        getContentPane().add(time2TF);
        time2TF.setBounds(920, 200, 90, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/customerbooking.png"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(1338, 768));
        background.setMinimumSize(new java.awt.Dimension(1338, 768));
        background.setPreferredSize(new java.awt.Dimension(1338, 768));
        getContentPane().add(background);
        background.setBounds(0, 0, 1370, 768);

        logoutBT.setText("jButton1");
        getContentPane().add(logoutBT);
        logoutBT.setBounds(1200, 20, 130, 60);

        searchBT.setText("jButton1");
        getContentPane().add(searchBT);
        searchBT.setBounds(1050, 160, 270, 120);

        returnBT.setText("jButton1");
        getContentPane().add(returnBT);
        returnBT.setBounds(20, 20, 150, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void time1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time1TFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField ddateTF;
    private javax.swing.JTextField locationTF;
    private javax.swing.JButton logoutBT;
    private javax.swing.JTextField pdateTF;
    private javax.swing.JButton returnBT;
    private javax.swing.JButton searchBT;
    private javax.swing.JTextField time1TF;
    private javax.swing.JTextField time2TF;
    // End of variables declaration//GEN-END:variables
}
