/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author yibei
 */
public class cus_payment extends javax.swing.JFrame {
    String username;
    String price;
    /**
     * Creates new form cus_payment
     */
    public cus_payment() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }
    
    public cus_payment(String username,String price) {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
        this.username = username;
        this.price = price;
        displayamount.setText(this.price);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rm = new javax.swing.JLabel();
        cvc = new javax.swing.JPasswordField();
        cardnum = new javax.swing.JPasswordField();
        year = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        displayamount = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        payBT = new javax.swing.JButton();
        returnBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        rm.setFont(new java.awt.Font("Engravers MT", 0, 50)); // NOI18N
        rm.setText("RM");
        getContentPane().add(rm);
        rm.setBounds(110, 200, 340, 140);

        cvc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(cvc);
        cvc.setBounds(900, 500, 120, 50);

        cardnum.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(cardnum);
        cardnum.setBounds(1030, 330, 280, 50);

        year.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        getContentPane().add(year);
        year.setBounds(1220, 500, 100, 50);

        month.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        getContentPane().add(month);
        month.setBounds(1090, 500, 100, 50);

        name.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        getContentPane().add(name);
        name.setBounds(1030, 240, 280, 50);

        displayamount.setFont(new java.awt.Font("Engravers MT", 0, 50)); // NOI18N
        displayamount.setForeground(new java.awt.Color(48, 34, 140));
        getContentPane().add(displayamount);
        displayamount.setBounds(240, 200, 340, 140);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/cus_payment.png"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(1366, 768));
        background.setMinimumSize(new java.awt.Dimension(1366, 768));
        background.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(background);
        background.setBounds(0, -20, 1366, 800);

        payBT.setText("jButton1");
        getContentPane().add(payBT);
        payBT.setBounds(960, 640, 200, 80);

        returnBT.setText("jButton1");
        returnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTActionPerformed(evt);
            }
        });
        getContentPane().add(returnBT);
        returnBT.setBounds(30, 10, 150, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTActionPerformed
        // TODO add your handling code here:
        new cus_managebooking(this.username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cus_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cus_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cus_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cus_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cus_payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPasswordField cardnum;
    private javax.swing.JPasswordField cvc;
    private javax.swing.JLabel displayamount;
    private javax.swing.JTextField month;
    private javax.swing.JTextField name;
    private javax.swing.JButton payBT;
    private javax.swing.JButton returnBT;
    private javax.swing.JLabel rm;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
