/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yibei
 */
public class Customerpage extends javax.swing.JFrame {

    /**
     * Creates new form Customerpage
     */
    public Customerpage() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }

    public Customerpage(String username) {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
        this.username = username;
    }

    String username;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();
        mailBT = new javax.swing.JButton();
        makebookingBT = new javax.swing.JButton();
        managebookingBT = new javax.swing.JButton();
        manageaccountBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1338, 768));
        getContentPane().setLayout(null);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/customerpage.png"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(1338, 768));
        background.setMinimumSize(new java.awt.Dimension(1338, 768));
        background.setPreferredSize(new java.awt.Dimension(1338, 768));
        getContentPane().add(background);
        background.setBounds(0, 0, 1370, 770);

        mailBT.setText("jButton1");
        getContentPane().add(mailBT);
        mailBT.setBounds(20, 240, 130, 100);

        makebookingBT.setText("jButton1");
        makebookingBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makebookingBTActionPerformed(evt);
            }
        });
        getContentPane().add(makebookingBT);
        makebookingBT.setBounds(100, 610, 230, 110);

        managebookingBT.setText("jButton1");
        managebookingBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managebookingBTActionPerformed(evt);
            }
        });
        getContentPane().add(managebookingBT);
        managebookingBT.setBounds(570, 620, 230, 100);

        manageaccountBT.setText("jButton1");
        getContentPane().add(manageaccountBT);
        manageaccountBT.setBounds(1050, 610, 240, 110);

        logoutBT.setText("jButton1");
        logoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBT);
        logoutBT.setBounds(1190, 20, 140, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        new Startpage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutBTActionPerformed

    private void managebookingBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managebookingBTActionPerformed
        // TODO add your handling code here:
        new cus_managebooking(this.username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_managebookingBTActionPerformed

    private void makebookingBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makebookingBTActionPerformed
        // TODO add your handling code here:
        FileReader file;
        int flag = 1;
        try {
            file = new FileReader("cusbooking.txt");
            BufferedReader br = new BufferedReader(file);
            String line;
            while ((line = br.readLine()) != null) {
                String[] info = line.split(",");
                if (info[11].equals(this.username) & info[9].equals("nopayment")) {
                    JOptionPane.showMessageDialog(null, "Please make payment first :)");
                    flag = 0;
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Customerpage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Customerpage.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (flag == 1) {
            new Customer_Booking(this.username).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_makebookingBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customerpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton logoutBT;
    private javax.swing.JButton mailBT;
    private javax.swing.JButton makebookingBT;
    private javax.swing.JButton manageaccountBT;
    private javax.swing.JButton managebookingBT;
    // End of variables declaration//GEN-END:variables
}
